package observability

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Ingestion metrics
var (
	// FilesProcessedTotal tracks total files processed by document type and status
	FilesProcessedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_ingestion_files_total",
			Help: "Total number of files processed",
		},
		[]string{"document_type", "status"}, // status: success, failed
	)

	// RowsParsedTotal tracks total rows parsed by document type
	RowsParsedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_ingestion_rows_parsed_total",
			Help: "Total number of rows parsed from files",
		},
		[]string{"document_type"},
	)

	// TransactionsInsertedTotal tracks transactions inserted into database
	TransactionsInsertedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_ingestion_transactions_inserted_total",
			Help: "Total number of transactions inserted",
		},
		[]string{"tenant_id"},
	)

	// IngestionDuration tracks file processing duration
	IngestionDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "cashflow_ingestion_duration_seconds",
			Help:    "Duration of file ingestion process",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"document_type"},
	)

	// ParsingErrorsTotal tracks parsing errors
	ParsingErrorsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_ingestion_parsing_errors_total",
			Help: "Total number of parsing errors",
		},
		[]string{"document_type", "error_type"},
	)
)

// Pipeline metrics
var (
	// PipelineExecutionsTotal tracks pipeline executions
	PipelineExecutionsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_pipeline_executions_total",
			Help: "Total number of pipeline executions",
		},
		[]string{"status"}, // status: success, failed
	)

	// PipelineStepDuration tracks duration of each pipeline step
	PipelineStepDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "cashflow_pipeline_step_duration_seconds",
			Help:    "Duration of individual pipeline steps",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"step"},
	)

	// PipelineStepFailuresTotal tracks failures per step
	PipelineStepFailuresTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_pipeline_step_failures_total",
			Help: "Total number of pipeline step failures",
		},
		[]string{"step"},
	)

	// PipelineTotalDuration tracks total pipeline execution time
	PipelineTotalDuration = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "cashflow_pipeline_total_duration_seconds",
			Help:    "Total duration of complete pipeline execution",
			Buckets: []float64{1, 5, 10, 30, 60, 120, 300},
		},
	)
)

// Analysis metrics
var (
	// AnalysisHealthScore tracks health scores generated
	AnalysisHealthScore = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "cashflow_analysis_health_score",
			Help:    "Health scores generated by analysis",
			Buckets: []float64{0, 20, 40, 60, 80, 100},
		},
		[]string{"tenant_id"},
	)

	// AnalysisRunwayDays tracks runway days calculated
	AnalysisRunwayDays = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "cashflow_analysis_runway_days",
			Help:    "Runway days calculated by analysis",
			Buckets: []float64{0, 7, 14, 30, 60, 90, 180, 365},
		},
		[]string{"tenant_id"},
	)

	// AnalysisRiskLevel tracks risk level distribution
	AnalysisRiskLevel = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_analysis_risk_level_total",
			Help: "Total analyses by risk level",
		},
		[]string{"risk_level"}, // healthy, warning, critical
	)
)

// Event metrics
var (
	// EventsPublishedTotal tracks events published to NATS
	EventsPublishedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_events_published_total",
			Help: "Total number of events published",
		},
		[]string{"subject", "status"}, // status: success, failed
	)

	// EventsConsumedTotal tracks events consumed
	EventsConsumedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_events_consumed_total",
			Help: "Total number of events consumed",
		},
		[]string{"subject", "status"}, // status: success, failed, retried
	)

	// EventProcessingDuration tracks event processing time
	EventProcessingDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "cashflow_event_processing_duration_seconds",
			Help:    "Duration of event processing",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"subject"},
	)
)

// Database metrics
var (
	// DatabaseQueriesTotal tracks database queries
	DatabaseQueriesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_database_queries_total",
			Help: "Total number of database queries",
		},
		[]string{"operation", "status"}, // operation: select, insert, update, delete
	)

	// DatabaseQueryDuration tracks query duration
	DatabaseQueryDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "cashflow_database_query_duration_seconds",
			Help:    "Duration of database queries",
			Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5},
		},
		[]string{"operation"},
	)
)
